# See https://starship.rs/config/

command_timeout = 1000

[directory]
truncation_symbol = "…/"

[package]
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[aws]
disabled = true
