[character]
# Looks best with Nerd Fonts
symbol = " "

[directory]
truncate_to_repo = false

[package]
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[aws]
disabled = true

[env_var]
variable = "TOOLBOX_EMOJI"
style = "red"
