# See https://starship.rs/config/

command_timeout = 1000

[directory]
truncation_symbol = "…/"

[package]
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[aws]
disabled = true

# Configs below look best with Nerd Fonts

# [character]
# success_symbol = " "
# error_symbol = "[ ](red)"

# [battery]
# full_symbol = ""
# charging_symbol = ""
# discharging_symbol = ""

# [env_var]
# symbol = ""
# variable = "TOOLBOX_PATH"
# format = "via $symbol"
