# See https://starship.rs/config/

[character]
# Looks best with Nerd Fonts
success_symbol = " "
error_symbol = "[ ](red)"

[directory]
truncation_symbol = "…/"

[package]
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[aws]
disabled = true
